### ISSUE TITLE
Set : Title and favicon of the page

### ISSUE THREAD

**Issue by Harsh-KumarJha** [aswathcm29/JournalForge#34]
I am a contributor under GSSoC'24 - EXTD and would love to work towards the project.
the current title for the website login page: Vite+ React
current favicon : default react 

I can set it to according to the page and will update the favicon.

Kindly assign this issue to me under GSSoC'24.

**Comment by aswathcm29** [comment]
Okay @Harsh-KumarJha ! let me assign it to you  , but before proceeding with the updation , kindly make sure to comment what image or icon you are going to update here ! if okay , lets proceed with the updates .

**Comment by Harsh-KumarJha** [comment]
Here is the image showcasing the tab title of the page along with the favicon.
![image](https://github.com/user-attachments/assets/3cf05ef5-787e-40d0-b5d6-8395e9718108)

**Comment by Harsh-KumarJha** [comment]
I would require some favicon that you would like to be for the page. If not available i can leave it as it is.

**Comment by Dhruv-pahuja** [comment]
I can see that there is no update on this issue so can you please assign this issue to me so that i can fix this quickly...
@Harsh-KumarJha  @aswathcm29

**Comment by Harsh-KumarJha** [comment]
@Dhruv-pahuja I am currently working on this and waiting for the favicon after which I will create a PR.
