### ISSUE TITLE
Update Navlink traversal

### ISSUE THREAD

**Issue by Vishesh-Tripathi** [aswathcm29/JournalForge#35]
when user clicks on Navlinks there should be an active color on tabs but here it is "Add your Journal" is always active 

![Screenshot 2024-10-01 190058](https://github.com/user-attachments/assets/f09dcb38-2099-41b2-bc16-fb31365e69af)

here you can see we are on home page but active tab is diiferent mean home is not green

**Comment by aswathcm29** [comment]
Yes @Vishesh-Tripathi let me assign it to you ! please make sure to follow the theme of the application !

**Comment by Vishesh-Tripathi** [comment]
sure
