### ISSUE TITLE
Journals section not able to scroll

### ISSUE THREAD

**Issue by Vaibhav-Kumar-K-R** [aswathcm29/JournalForge#37]
The journal section is not able to scroll in the x direction to further view more journals.
Please assign the isuue to me under GSSOC '24
![image](https://github.com/user-attachments/assets/205b3b39-bbdc-4fc3-b523-54380d0902fe)

**Comment by aswathcm29** [comment]
Could you please give me a reference on how are you planning to keep that scroll  @Vaibhav-Kumar-K-R  ?

**Comment by Vaibhav-Kumar-K-R** [comment]
Scroll in the x direction as mentioned
