### ISSUE TITLE
About us link in the footer section not redirecting properly.

### ISSUE THREAD

**Issue by Vaibhav-Kumar-K-R** [aswathcm29/JournalForge#39]
On clicking about us link in footer its not displaying the correct content
Solution:
Create a separate page for about us and link it 
Please assign the issue to me under GSSOC'24
![image](https://github.com/user-attachments/assets/f4391242-7402-46ea-8594-dbd04e2c1ae7)

**Comment by aswathcm29** [comment]
Okay ! @Vaibhav-Kumar-K-R Im assigning it you ! Make sure to follow the theme of the application

**Comment by Vaibhav-Kumar-K-R** [comment]
I have linked a pull request referenced #45 .
Please review .
