### ISSUE TITLE
On login and Sign-in page there is not password visible option which is not a good user experience

### ISSUE THREAD

**Issue by VinayLodhi1712** [aswathcm29/JournalForge#40]
## What feature would you like to see?
I want to add an icon fa-eye which helps  user to see the password which he/she is inserting.

## Why is this feature useful?
enhance user experience and help to check user password visibility while filling password.

## How important is this feature to you?
- [1] Must have
- [ ] Should have
- [ ] Nice to have
- [ ] Just an idea

## Have you seen this feature in other projects?
- [ 1] Yes, I've seen something similar elsewhere
- [ ] No, this is a unique idea

## Any other details?
Add any other information or screenshots about your feature idea here.
![registerpasseye](https://github.com/user-attachments/assets/1599ffc7-e17b-40d8-92db-068d14cf4233)
![loginpasseye](https://github.com/user-attachments/assets/05d935ea-0332-41a6-9bc7-385f874344d4)

so after adding my feature it will look like 
![showhide](https://github.com/user-attachments/assets/a7e0ee60-bb05-4d9c-b1e1-59f76735c6cd)

## Your experience level with this project:
- [ 1] I'm new here (first-time contributor)
- [ ] I've used this project before
- [ ] I've contributed to this project before

## Would you like to work on this feature?
- [1 ] Yes, I'd like to try implementing this feature
- [ ] I can help with testing
- [ ] I can help with documentation
- [ ] No, I'm just suggesting the idea

assign this issue under gssoc extended and hactoberfest

**Comment by Kunj05** [comment]
Can you assign me this issue under GSSOC

**Comment by aswathcm29** [comment]
> Can you assign me this issue under GSSOC

 Hey @Kunj05 ! I appreciate your request , You might have to check other issues for now. Thanks for understanding!

**Comment by VinayLodhi1712** [comment]
@aswathcm29 can you plz add level in it so it will be good for me to show and get points on gssoc leaderboard
