### ISSUE TITLE
Add Code of Conduct

### ISSUE THREAD

**Issue by aswathcm29** [aswathcm29/JournalForge#46]
Add code of conduct for the repository and hence its documentation can be enhanced !

**Comment by Itachii27** [comment]
Hi @aswathcm29 I want to work on this issue. Kindly assign this issue to me

**Comment by aswathcm29** [comment]
Okay @Itachii27 I'd assign it to you ! Make sure it is proper and suitable for the repo and application

**Comment by Itachii27** [comment]
Hi @aswathcm29 I have done. Kindly review the PR and please add the labels of gssoc-extd, hacktoberfest, hacktoberfest-accepted and level in the issue

**Comment by Itachii27** [comment]
Hi @aswathcm29 Kindly modify the label name to **gssoc-extd** and **level-1**. As it merged, please close this issue as well

**Comment by Itachii27** [comment]
@aswathcm29 Could you kindly modify the labels to **gssoc-extd**. As i'm working under that and you have mentioned **gssoc-etd** which won't be counted
