### ISSUE TITLE
Issue: Add hovering effects over the jounral cards make it more interactive 

### ISSUE THREAD

**Issue by Hh440** [aswathcm29/JournalForge#49]
## What feature would you like to see?
when the use hover over the journal card,the card scale will change a liitle bit giving it effect of floating

![Screenshot from 2024-10-02 10-34-42](https://github.com/user-attachments/assets/135fb28d-1c16-4b6c-ae1f-1541ee96e1db)

## Why is this feature useful?
make the interface more engaging to the user

## Have you seen this feature in other projects?
Yes, I've seen something similar elsewhere

## Your experience level with this project:
 I'm new here (first-time contributor)

## Would you like to work on this feature?
Yes, I'd like to try implementing this feature

**Comment by aswathcm29** [comment]
Hey @Hh440 that's a good one ! Im assigning it to you

**Comment by Hh440** [comment]
Please also add hacktoberfest label
