### ISSUE TITLE
feature enhancement : Dark mode toggle

### ISSUE THREAD

**Issue by T-Rahul-prabhu-38** [aswathcm29/JournalForge#67]
## What feature would you like to see?
there is no preferences in the website to toggle between dark and light mode.I will create a toggle in the navabar which will allow the user to toggle between dark mode and light mode. please assign me this task.

## Why is this feature useful?
This can be useful for the user to best suit is viewing preferences.

## How important is this feature to you?
- [ ] Must have
- [ ] Should have
- [X] Nice to have
- [ ] Just an idea

## Have you seen this feature in other projects?
- [X] Yes, I've seen something similar elsewhere
- [ ] No, this is a unique idea

## Your experience level with this project:
- [ ] I'm new here (first-time contributor)
- [X] I've used this project before
- [ ] I've contributed to this project before

## Would you like to work on this feature?
- [X] Yes, I'd like to try implementing this feature
- [ ] I can help with testing
- [ ] I can help with documentation
- [ ] No, I'm just suggesting the idea

**Comment by aswathcm29** [comment]
Haha ! @T-Rahul-prabhu-38 but there isn't any dark mode support in this application ! And hence it'd be fine if you raise some other issue which could enhance the application !
