### ISSUE TITLE
Remove the Author Field from the Create journal page

### ISSUE THREAD

**Issue by 0vai5** [aswathcm29/JournalForge#83]
I’d like to propose removing the author field from the "Add Journal" page. Instead of users having to fill in their name, we could automatically associate the journal entry with the currently logged-in user. This would make it easier to organize posts by user and help populate their profile pages more effectively.

I believe this change is important for improving user experience and reducing errors. I’ve seen similar implementations in other projects and think it could work well here.

As a first-time contributor, I’m excited about the possibility of helping to implement this feature. Could you please assign this feature request to me and add the label "gssoc-ext"? I’m eager to get started!

Thank you!

**Comment by aswathcm29** [comment]
Yeah @0vai5 ! Make sure to make the ui enhanced on the removal of the author in the "Add Journal " page  !
