### ISSUE TITLE
Feature : Adding Dockerfile to the root of the application

### ISSUE THREAD

**Issue by haseebzaki-07** [aswathcm29/JournalForge#84]
## What feature would you like to see?
I want to add Dockerfile for image formantion and containerization of the application.

## Why is this feature useful?
Docker can build images automatically by reading the instructions from a "Dockerfile" and then we can run the image using Docker without going through the steps for project setup on our local machines

## How important is this feature to you?
- [x ] Must have
- [ ] Should have
- [ ] Nice to have
- [ ] Just an idea

## Have you seen this feature in other projects?
- [x ] Yes, I've seen something similar elsewhere
- [ ] No, this is a unique idea

## Your experience level with this project:
- [x ] I'm new here (first-time contributor)
- [ ] I've used this project before
- [ ] I've contributed to this project before

## Would you like to work on this feature?
- [x ] Yes, I'd like to try implementing this feature
- [ ] I can help with testing
- [ ] I can help with documentation
- [ ] No, I'm just suggesting the idea

**Comment by aswathcm29** [comment]
Yeah that'd a great enhancement for the application @haseebzaki-07 ! I'm assigning it to you
